export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',

  // Not found
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',
  SEMESTER_NOT_FOUND = 'SEMESTER_NOT_FOUND',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  BED_NOT_FOUND = 'BED_NOT_FOUND',
  BILL_NOT_FOUND = 'BILL_NOT_FOUND',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_DATA = 'INVALID_DATA',
  INVALID_DATE = 'INVALID_DATE',
  EXCEL_INVALID_FORMAT = 'EXCEL_INVALID_FORMAT',
  EXCEL_IMPORT_FAILED = 'EXCEL_IMPORT_FAILED',
  EXCEL_IMPORT_ROLLED_BACK = 'EXCEL_IMPORT_ROLLED_BACK',

  // Semester
  SEMESTER_ALREADY_ACTIVE = 'SEMESTER_ALREADY_ACTIVE',
  SEMESTER_INVALID_STATUS = 'SEMESTER_INVALID_STATUS',
  SEMESTER_FINISHED_LOCKED = 'SEMESTER_FINISHED_LOCKED',
  SEMESTER_OVERLAP = 'SEMESTER_OVERLAP',
  SEMESTER_HAS_DATA = 'SEMESTER_HAS_DATA',

  // Room assignment
  ROOM_NOT_ENOUGH_CAPACITY = 'ROOM_NOT_ENOUGH_CAPACITY',
  ROOM_GENDER_MISMATCH = 'ROOM_GENDER_MISMATCH',
  ROOM_ASSIGNMENT_DUPLICATE_STUDENT = 'ROOM_ASSIGNMENT_DUPLICATE_STUDENT',
  ROOM_ASSIGNMENT_DUPLICATE_BED = 'ROOM_ASSIGNMENT_DUPLICATE_BED',
  ROOM_ASSIGNMENT_FAILED = 'ROOM_ASSIGNMENT_FAILED',
  ROOM_ASSIGNMENT_NOT_FOUND = 'ROOM_ASSIGNMENT_NOT_FOUND',

  // Utility billing
  UTILITY_USAGE_INVALID = 'UTILITY_USAGE_INVALID',
  UTILITY_BILL_ALREADY_EXISTS = 'UTILITY_BILL_ALREADY_EXISTS',
  UTILITY_BILL_ALREADY_PAID = 'UTILITY_BILL_ALREADY_PAID',
  UTILITY_BILL_OVERDUE = 'UTILITY_BILL_OVERDUE',

  // Payment
  PAYMENT_SIGNATURE_INVALID = 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_AMOUNT_INVALID = 'PAYMENT_AMOUNT_INVALID',
  PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // Generic
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
