const VARIANTS: Record<string, string> = {
  UNOPENED: 'bg-status-muted-bg text-status-muted-text',
  ACTIVE: 'bg-status-active-bg text-status-active-text',
  PREPARING: 'bg-status-pending-bg text-status-pending-text',
  FINISHED: 'bg-status-completed-bg text-status-completed-text',
  RESIDING: 'bg-status-active-bg text-status-active-text',
  NOT_RESIDING: 'bg-status-muted-bg text-status-muted-text',
  PENDING_ROOM: 'bg-status-pending-bg text-status-pending-text',
  AVAILABLE: 'bg-status-completed-bg text-status-completed-text',
  OCCUPIED: 'bg-status-active-bg text-status-active-text',
  MAINTENANCE: 'bg-status-pending-bg text-status-pending-text',
  BROKEN: 'bg-status-error-bg text-status-error-text',
  INACTIVE: 'bg-status-muted-bg text-status-muted-text',
  LOCKED: 'bg-status-error-bg text-status-error-text',
  MALE: 'bg-status-active-bg text-status-active-text',
  FEMALE: 'bg-[#FCE7F3] text-[#BE185D]',
  PAID: 'bg-status-completed-bg text-status-completed-text',
  SENT: 'bg-status-completed-bg text-status-completed-text',
  RESOLVED: 'bg-status-completed-bg text-status-completed-text',
  SUCCESS: 'bg-status-completed-bg text-status-completed-text',
  UNPAID: 'bg-status-pending-bg text-status-pending-text',
  PENDING: 'bg-status-pending-bg text-status-pending-text',
  RECORDED: 'bg-status-pending-bg text-status-pending-text',
  OVERDUE: 'bg-status-error-bg text-status-error-text',
  FAILED: 'bg-status-error-bg text-status-error-text',
  REJECTED: 'bg-status-error-bg text-status-error-text',
  CANCELLED: 'bg-status-muted-bg text-status-muted-text',
  ENDED: 'bg-status-muted-bg text-status-muted-text',
  PROCESSING: 'bg-status-active-bg text-status-active-text',
  ADMIN: 'bg-[#EDE9FE] text-[#7C3AED]',
  MANAGER: 'bg-status-active-bg text-status-active-text',
  STUDENT: 'bg-status-pending-bg text-status-pending-text',
  GENERAL: 'bg-status-active-bg text-status-active-text',
  PRIVATE: 'bg-[#FCE7F3] text-[#BE185D]',
  SEMESTER_1: 'bg-status-active-bg text-status-active-text',
  SEMESTER_2: 'bg-status-pending-bg text-status-pending-text',
  SUMMER: 'bg-status-completed-bg text-status-completed-text',
  REQUEST: 'bg-status-active-bg text-status-active-text',
  COMPLAINT: 'bg-status-error-bg text-status-error-text',
  FEEDBACK: 'bg-status-completed-bg text-status-completed-text',
  CASH_PAYMENT: 'bg-status-pending-bg text-status-pending-text',
  OTHER: 'bg-status-muted-bg text-status-muted-text',
  IN_PROGRESS: 'bg-status-active-bg text-status-active-text',
  DRAFT: 'bg-status-pending-bg text-status-pending-text',
  PUBLISHED: 'bg-status-completed-bg text-status-completed-text',
  ARCHIVED: 'bg-status-muted-bg text-status-muted-text',
  CREATE_STUDENT: 'bg-[#D1FAE5] text-[#065F46]',
  CREATE_ACCOUNT: 'bg-[#DBEAFE] text-[#1E40AF]',
  RE_REGISTER: 'bg-[#FEF3C7] text-[#92400E]',
  VALID: 'bg-status-completed-bg text-status-completed-text',
};

const LABELS: Record<string, string> = {
  ADMIN: 'Quản trị viên',
  MANAGER: 'Cán bộ quản lý',
  STUDENT: 'Sinh viên',
  ACTIVE: 'Hoạt động',
  INACTIVE: 'Không hoạt động',
  LOCKED: 'Đã khóa',
  UNOPENED: 'Chưa mở',
  PREPARING: 'Chuẩn bị',
  FINISHED: 'Kết thúc',
  RESIDING: 'Đã có phòng',
  NOT_RESIDING: 'Không ở',
  PENDING_ROOM: 'Chưa có phòng',
  MALE: 'Nam',
  FEMALE: 'Nữ',
  AVAILABLE: 'Trống',
  OCCUPIED: 'Đã sử dụng',
  MAINTENANCE: 'Bảo trì',
  BROKEN: 'Hỏng',
  PAID: 'Đã thanh toán',
  UNPAID: 'Chưa thanh toán',
  OVERDUE: 'Quá hạn',
  PENDING: 'Chờ xử lý',
  RESOLVED: 'Đã giải quyết',
  REJECTED: 'Đã từ chối',
  CANCELLED: 'Đã hủy',
  PROCESSING: 'Đang xử lý',
  IN_PROGRESS: 'Đang xử lý',
  RECORDED: 'Chờ xử lý',
  SUCCESS: 'Thành công',
  FAILED: 'Thất bại',
  SENT: 'Đã gửi',
  ENDED: 'Kết thúc',
  GENERAL: 'Chung',
  PRIVATE: 'Riêng',
  SEMESTER_1: 'Kỳ 1',
  SEMESTER_2: 'Kỳ 2',
  SUMMER: 'Kỳ hè',
  REQUEST: 'Yêu cầu',
  COMPLAINT: 'Khiếu nại',
  FEEDBACK: 'Góp ý',
  CASH_PAYMENT: 'Thanh toán tiền mặt',
  OTHER: 'Khác',
  DRAFT: 'Bản nháp',
  PUBLISHED: 'Đã công bố',
  ARCHIVED: 'Lưu trữ',
  CREATE_STUDENT: 'Tạo mới',
  CREATE_ACCOUNT: 'Tạo tài khoản',
  RE_REGISTER: 'Tái đăng ký',
  VALID: 'Hợp lệ',
};

export function Badge({ value, className = '' }: { value: string; className?: string }) {
  const variant = VARIANTS[value] || 'bg-status-muted-bg text-status-muted-text';
  const label = LABELS[value] || value;
  return (
    <span className={`inline-block rounded-[var(--radius-pill)] px-3 py-1 text-xs font-semibold ${variant} ${className}`}>
      {label}
    </span>
  );
}

export function roleLabel(role: string): string {
  return LABELS[role] || role;
}
